#!/usr/bin/env bash
# Script: 3-redirection

# Install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Add a 301 redirect inside default server block using sed
sudo sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
